# -*- coding: utf-8 -*-
"""Web Scraping para ver valor dolar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z12vVxkVEuUBS19PLZ0VdtxsE64Efww5
"""

from bs4 import BeautifulSoup
import requests
import lxml
import numpy as np

url = 'https://www.dolarhoy.com/'
header = {"User-Agent": 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'}

page = requests.get(url, headers=header)
soup = BeautifulSoup(page.content, 'html.parser')

precios = soup.find_all("span", class_ ="price")
print('Dolar Ofiofi: %s' % precios[8].get_text().strip())
for el in precios[0:2]:
  print('Dolar Oficial: %s' % el.get_text().strip())
for el in precios[2:4]:
  print('Dolar Blue: %s' % el.get_text().strip())
for el in precios[4:6]:
  print('Dolar Bolsa: %s' % el.get_text().strip())
for el in precios[6:8]:
  print('Dolar Liqui: %s' % el.get_text().strip())
for el in precios[9:11]:
  print('Dolar BullExchange: %s' % el.get_text().strip())